In [148]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [149]:
df = pd.read_csv("C:\\Users\\Ketan Gangal\\OneDrive\\Desktop\\python_basic\\Ml\\00 ml_course\\08-Linear-Regression-Models\\Advertising.csv")

In [150]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [151]:
X = df.drop('sales',axis=1)

In [152]:
y = df['sales']

In [153]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [154]:
y.head()

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
Name: sales, dtype: float64

In [155]:
# Feature Expansion

In [156]:
from sklearn.preprocessing import PolynomialFeatures

In [157]:
polynomial_converter = PolynomialFeatures(degree=3,include_bias=False)

In [158]:
polynomial_converter.fit(X)

PolynomialFeatures(degree=3, include_bias=False)

In [159]:
polynomial_features = polynomial_converter.transform(X)

In [160]:
polynomial_features.shape

(200, 19)

In [161]:
from sklearn.model_selection import train_test_split

In [162]:
X_train, X_test, y_train, y_test = train_test_split(polynomial_features, y, test_size=0.30, random_state=101)

In [163]:
X_train.shape

(140, 19)

In [164]:
# Feature Scaling

In [165]:
from sklearn.preprocessing import StandardScaler

In [166]:
scaler = StandardScaler()

In [167]:
# scale fit only on train to avoide leakage
scaler.fit(X_train)

StandardScaler()

In [168]:
X_train = scaler.transform(X_train)

In [169]:
X_test = scaler.transform(X_test)

In [170]:
polynomial_features[0]

array([2.30100000e+02, 3.78000000e+01, 6.92000000e+01, 5.29460100e+04,
       8.69778000e+03, 1.59229200e+04, 1.42884000e+03, 2.61576000e+03,
       4.78864000e+03, 1.21828769e+07, 2.00135918e+06, 3.66386389e+06,
       3.28776084e+05, 6.01886376e+05, 1.10186606e+06, 5.40101520e+04,
       9.88757280e+04, 1.81010592e+05, 3.31373888e+05])

In [171]:
X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

In [172]:
# Regularization Techniques

**Ridge Regression(L2)**

In [173]:
from sklearn.linear_model import Ridge

In [174]:
#help(Ridge)

In [175]:
ridge_model = Ridge(alpha=10)

In [176]:
ridge_model.fit(X_train,y_train)

Ridge(alpha=10)

In [177]:
ridge_pred = ridge_model.predict(X_test)

In [178]:
from sklearn.metrics import mean_squared_error,mean_absolute_error

In [179]:
MAE = mean_absolute_error(y_test,ridge_pred)

In [180]:
RMSE = np.sqrt(mean_squared_error(y_test,ridge_pred))

In [181]:
MAE

0.5774404204714183

In [182]:
RMSE

0.8946386461319685

In [183]:
from sklearn.linear_model import RidgeCV

In [184]:
ridge_cv_model = RidgeCV(alphas=(0.1,1,10),scoring='neg_mean_absolute_error')

In [185]:
ridge_cv_model.fit(X_train,y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), scoring='neg_mean_absolute_error')

In [186]:
ridge_cv_model.alpha_

0.1

In [193]:
ridge_cv_model.best_score_

-0.3749223340292957

In [83]:
from sklearn.metrics import SCORERS

In [84]:
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_weighted'])

In [90]:
ridge_pred = ridge_cv_model.predict(X_test)

In [92]:
MAE = mean_absolute_error(y_test,ridge_pred)

In [93]:
RMSE = np.sqrt(mean_squared_error(y_test,ridge_pred))

In [94]:
MAE

0.42737748843352086

In [95]:
RMSE

0.6180719926924644

**LASSO: least absolute shrinkage and selection operator**

In [194]:
from sklearn.linear_model import LassoCV

In [195]:
lasso_cv_model = LassoCV(eps=0.0001, n_alphas=100, alphas=None,cv =5,max_iter=1000000)

In [196]:
lasso_cv_model.fit(X_train,y_train)

LassoCV(cv=5, eps=0.0001, max_iter=1000000)

In [197]:
lasso_cv_model.alpha_

0.0015095424326693491

In [128]:
lasso_pred = lasso_cv_model.predict(X_test)

In [129]:
MAE = mean_absolute_error(y_test,lasso_pred)

In [130]:
RMSE = np.sqrt(mean_squared_error(y_test,lasso_pred))

In [131]:
MAE

0.3855089228001998

In [132]:
RMSE

0.5552329392967783

In [109]:
#eps=0.1, n_alphas=100, alphas=None,cv =5 
# most of them are zero performance is quite impressive
# Easy to interpret 
lasso_cv_model.coef_

array([1.002651  , 0.        , 0.        , 0.        , 3.79745279,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

In [112]:
MAE

0.6541723161252854

In [113]:
RMSE

1.130800102276253

In [121]:
#eps=0.001, n_alphas=100, alphas=None,cv =5,max_iter = 1000000
# still less features but hight performance then Ridge and Normal liner regression
lasso_cv_model.coef_

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])

In [122]:
MAE

0.43350346185900673

In [123]:
RMSE

0.6063140748984039

In [133]:
lasso_cv_model.coef_

array([ 6.52215309,  0.19529545,  0.39169742, -8.8999717 ,  4.70179884,
       -0.85716988, -0.15428604,  0.13599638, -0.        ,  4.13247739,
       -1.06650388,  0.64747822,  0.27820331, -0.21513583, -0.        ,
       -0.        , -0.        , -0.        , -0.05440358])

In [134]:
MAE

0.3855089228001998

In [135]:
RMSE

0.5552329392967783

**ElasticNetCV**

In [136]:
from sklearn.linear_model import ElasticNetCV

In [137]:
elastic_model = ElasticNetCV(l1_ratio=[.1, .5, .7, .9, .95, .99, 1],eps=0.001,n_alphas=100,max_iter=1000000)

In [138]:
elastic_model.fit(X_train,y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=1000000)

In [139]:
elastic_pred = elastic_model.predict(X_test)

In [140]:
MSE = mean_absolute_error(y_test,elastic_pred)

In [141]:
RMSE = np.sqrt(mean_squared_error(y_test,elastic_pred))

In [142]:
MSE

0.43350346185900673

In [143]:
RMSE

0.6063140748984039

In [144]:
elastic_model.coef_

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])

In [145]:
elastic_model.l1_ratio_

1.0

In [146]:
elastic_model.alpha_

0.004943070909225827

In [147]:
lasso_cv_model.alpha_

0.0015095424326693491