# Numpy notebook


In [1]:
import numpy as np

In [2]:
lis = [1,2,3,4]

In [3]:
arr = np.array(lis)

In [4]:
# only 1d are called as vector
arr

array([1, 2, 3, 4])

In [5]:
lis

[1, 2, 3, 4]

In [6]:
# 2d and above are called as matrix
lis = [[1,2,3],[4,5,6],[8,9,0]]

In [7]:
lis

[[1, 2, 3], [4, 5, 6], [8, 9, 0]]

In [8]:
np.array(lis)

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 0]])

In [9]:
#built in 
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.zeros(5,dtype = int)

array([0, 0, 0, 0, 0])

In [14]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [16]:
np.eye(4,4,0)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [18]:
np.random.rand(5)

array([0.04522183, 0.8421663 , 0.83888387, 0.18535571, 0.78671962])

In [19]:
np.random.rand(5,5)

array([[0.29173925, 0.0641644 , 0.49361682, 0.83035013, 0.57550398],
       [0.04956013, 0.71319646, 0.60272841, 0.22639742, 0.16367824],
       [0.75055584, 0.18370057, 0.56782654, 0.31471158, 0.38890458],
       [0.3514766 , 0.66158393, 0.13168397, 0.54485374, 0.16555356],
       [0.74130063, 0.79758857, 0.95152809, 0.52195896, 0.52546052]])

In [20]:
np.random.randn(5)

array([-1.38339875,  0.67255417, -1.22565827, -0.25287001, -0.55302366])

In [21]:
np.random.randn(5,5)

array([[ 1.91051055, -0.83571341, -1.28552827, -0.30134387, -1.30892891],
       [ 0.3994807 , -0.7531435 , -0.0895542 , -0.72094329, -0.79461839],
       [-0.35342106, -0.52163582, -1.65992847, -0.36246052,  0.16601062],
       [-0.37150835,  0.35402916,  0.54087044, -1.09602953,  0.67311512],
       [ 0.85561783,  1.7188653 , -0.1790582 , -1.00776395, -1.34152376]])

In [22]:
np.random.randint(0,5,(6,4)) 

array([[1, 2, 0, 3],
       [3, 1, 1, 3],
       [2, 0, 4, 0],
       [1, 0, 4, 0],
       [0, 0, 4, 4],
       [4, 4, 3, 1]])

In [23]:
np.random.randint(0,11,(2,5))

array([[8, 8, 0, 8, 2],
       [0, 8, 9, 3, 9]])

In [24]:
np.random.seed(12)
np.random.randint(1,5)

4

In [25]:
np.random.seed(12)
np.random.randint(1,5)

4

In [26]:
arr  = np.random.randint(0,12,(2,2))

In [27]:
arr

array([[11,  6],
       [ 1,  2]])

In [28]:
arr.max()

11

In [29]:
arr.min()

1

In [30]:
arr.argmax()

0

In [31]:
arr.argmin()

2

In [32]:
arr.dtype

dtype('int32')

In [33]:
arr.shape

(2, 2)

In [34]:
arr.reshape(1,4)

array([[11,  6,  1,  2]])

In [35]:
arr = arr.reshape(4,1)

In [36]:
arr.shape

(4, 1)

# indexing and slicing 

In [37]:
arr = np.arange(0,11)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr[0]

0

In [41]:
arr[5]

5

In [42]:
arr[:5]

array([0, 1, 2, 3, 4])

In [43]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr[:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
#similar to list
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

# Broadcasting

In [47]:
arr = np.arange(0,11)

In [57]:
l = [1,2,3,344,5,6]

In [58]:
l[1:4]= 100

TypeError: can only assign an iterable

In [52]:
arr[1:4] = 100

In [53]:
arr

array([  0, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [54]:
arrr = arr[1:4]

In [55]:
li = l[1:4]

In [59]:
li[0] = 700

In [60]:
l

[1, 2, 3, 344, 5, 6]

In [61]:
li

[700, 3, 344]

In [62]:
arrr[0] = 700

In [63]:
arr

array([  0, 700, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [64]:
arr

array([  0, 700, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [65]:
arrr = arr.copy()

In [68]:
arrr[0:2] = 200

In [69]:
arrr

array([200, 200, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [70]:
arr

array([  0, 700, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [72]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [73]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
arr_2d[0]

array([1, 2, 3])

In [99]:
arr_2d[1][2]

6

In [100]:
arr_2d[1,2]

6

In [101]:
arr_2d[:,0]

array([1, 4, 7])

# conditional statement

In [104]:
arr = np.arange(0,11)

In [107]:
arr = arr[::-1]

In [108]:
arr

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [109]:
arr>4

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False])

In [110]:
arr[arr>4]

array([10,  9,  8,  7,  6,  5])

# operations

In [111]:
arr = np.arange(0,11)

In [121]:
arr +5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [122]:
arr -5

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [123]:
arr *5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [124]:
arr / 5

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [125]:
arr / arr

C:\Users\Ketan Gangal\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [126]:
1/arr

C:\Users\Ketan Gangal\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [127]:
arr +arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [128]:
np.log(arr)

C:\Users\Ketan Gangal\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [129]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [130]:
np.max(arr)

10

In [131]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [132]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [133]:
np.mean(arr)

5.0

In [134]:
arr.mean()

5.0

In [135]:
arr.var()

10.0

In [136]:
arr.std()

3.1622776601683795

# axis

In [137]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [138]:
arr_2d.sum()

45

In [139]:
arr_2d.shape

(3, 3)

In [141]:
arr_2d.sum(axis=0)

array([12, 15, 18])

In [142]:
arr_2d.sum(axis = 1)

array([ 6, 15, 24])